/** @jsx jsx */
import { jsx } from "@emotion/core"
import { useState, SyntheticEvent } from "react"

import Link from "next/link"

import { capitalizeFirstLetter } from "../common/utils"
import { TYPES } from "../common/constants"
import { Theme, SearchInputOption } from "../common/types"

import SearchIcon from "@material-ui/icons/Search"
import Autocomplete, {
  AutocompleteRenderInputParams,
} from "@material-ui/lab/Autocomplete"
import { Popper, PopperProps } from "@material-ui/core"

const ComboBox = () => {
  const [open, setOpen] = useState(false)
  const [userInput, setUserInput] = useState<string>("")

  const handleInputChange = (event: SyntheticEvent, value: string) => {
    setUserInput(value)
  }

  const CustomPopper = (props: PopperProps) => (
    <Popper
      {...props}
      css={(theme: Theme) => ({
        border: `solid 0.5px ${theme.header.button.border}`,
        borderTop: "none",
        backgroundColor: theme.input.background,
        width: 300,
        "& > .MuiPaper-root": {
          backgroundColor: theme.input.background,
          fontFamily: theme.body.font,
        },
        "& > div > ul > li": {
          borderBottom: "solid 1px #E31010",
          "&:hover": { backgroundColor: "auto" },
        },
        "& > div > .MuiAutocomplete-noOptions": {
          color: theme.input.text,
        },
      })}
      placement="bottom-start"
    />
  )

  const getTypeFromOption = (type: string): string => {
    switch (type) {
      case "Pokemon":
        return "pokemon"
      case "Type":
        return "types"
    }
  }

  const center = { display: "flex", alignItems: "center" }
  const centerAndSpace = {
    ...center,
    justifyContent: "space-between",
  }

  const renderInput = (params: AutocompleteRenderInputParams) => (
    <div ref={params.InputProps.ref} css={{ ...centerAndSpace }}>
      <SearchIcon
        css={{
          margin: "0 5px",
          "&:hover": { cursor: "pointer" },
        }}
      />
      <input
        placeholder="Search..."
        css={(theme) => ({
          width: "auto",
          backgroundColor: theme.input.background,
        })}
        type="text"
        {...params.inputProps}
      />
    </div>
  )

  const renderOption = (option: SearchInputOption) => (
    <div css={{ ...centerAndSpace, width: "100%" }}>
      <Link href={`/${getTypeFromOption(option.type)}/${option.id}`}>
        <a
          css={(theme) => ({
            width: "100%",
            color: theme.input.text,
          })}
        >
          {capitalizeFirstLetter(option.identifier)}
        </a>
      </Link>
      <span css={(theme) => ({ fontSize: "0.66em", color: theme.input.text })}>
        <i>{option.type}</i>
      </span>
    </div>
  )

  return (
    <Autocomplete
      css={{ width: "100%" }}
      id="headerAutoComplete"
      open={open && userInput.length > 2}
      onOpen={() => {
        setOpen(true)
      }}
      onClose={() => {
        setOpen(false)
      }}
      onInputChange={handleInputChange}
      options={[...pokemons, ...types]}
      getOptionLabel={(pokemon) => pokemon.identifier}
      renderInput={(params) => renderInput(params)}
      renderOption={(option) => renderOption(option)}
      noOptionsText="No result found."
      PopperComponent={CustomPopper}
    />
  )
}

const HeaderInputBase = () => {
  return <ComboBox />
}

const pokemons: Array<SearchInputOption> = [
  { id: 1, type: "Pokemon", identifier: "bulbasaur" },
  { id: 2, type: "Pokemon", identifier: "ivysaur" },
  { id: 3, type: "Pokemon", identifier: "venusaur" },
  { id: 4, type: "Pokemon", identifier: "charmander" },
  { id: 5, type: "Pokemon", identifier: "charmeleon" },
  { id: 6, type: "Pokemon", identifier: "charizard" },
  { id: 7, type: "Pokemon", identifier: "squirtle" },
  { id: 8, type: "Pokemon", identifier: "wartortle" },
  { id: 9, type: "Pokemon", identifier: "blastoise" },
  { id: 10, type: "Pokemon", identifier: "caterpie" },
  { id: 11, type: "Pokemon", identifier: "metapod" },
  { id: 12, type: "Pokemon", identifier: "butterfree" },
  { id: 13, type: "Pokemon", identifier: "weedle" },
  { id: 14, type: "Pokemon", identifier: "kakuna" },
  { id: 15, type: "Pokemon", identifier: "beedrill" },
  { id: 16, type: "Pokemon", identifier: "pidgey" },
  { id: 17, type: "Pokemon", identifier: "pidgeotto" },
  { id: 18, type: "Pokemon", identifier: "pidgeot" },
  { id: 19, type: "Pokemon", identifier: "rattata" },
  { id: 20, type: "Pokemon", identifier: "raticate" },
  { id: 21, type: "Pokemon", identifier: "spearow" },
  { id: 22, type: "Pokemon", identifier: "fearow" },
  { id: 23, type: "Pokemon", identifier: "ekans" },
  { id: 24, type: "Pokemon", identifier: "arbok" },
  { id: 25, type: "Pokemon", identifier: "pikachu" },
  { id: 26, type: "Pokemon", identifier: "raichu" },
  { id: 27, type: "Pokemon", identifier: "sandshrew" },
  { id: 28, type: "Pokemon", identifier: "sandslash" },
  { id: 29, type: "Pokemon", identifier: "nidoran-f" },
  { id: 30, type: "Pokemon", identifier: "nidorina" },
  { id: 31, type: "Pokemon", identifier: "nidoqueen" },
  { id: 32, type: "Pokemon", identifier: "nidoran-m" },
  { id: 33, type: "Pokemon", identifier: "nidorino" },
  { id: 34, type: "Pokemon", identifier: "nidoking" },
  { id: 35, type: "Pokemon", identifier: "clefairy" },
  { id: 36, type: "Pokemon", identifier: "clefable" },
  { id: 37, type: "Pokemon", identifier: "vulpix" },
  { id: 38, type: "Pokemon", identifier: "ninetales" },
  { id: 39, type: "Pokemon", identifier: "jigglypuff" },
  { id: 40, type: "Pokemon", identifier: "wigglytuff" },
  { id: 41, type: "Pokemon", identifier: "zubat" },
  { id: 42, type: "Pokemon", identifier: "golbat" },
  { id: 43, type: "Pokemon", identifier: "oddish" },
  { id: 44, type: "Pokemon", identifier: "gloom" },
  { id: 45, type: "Pokemon", identifier: "vileplume" },
  { id: 46, type: "Pokemon", identifier: "paras" },
  { id: 47, type: "Pokemon", identifier: "parasect" },
  { id: 48, type: "Pokemon", identifier: "venonat" },
  { id: 49, type: "Pokemon", identifier: "venomoth" },
  { id: 50, type: "Pokemon", identifier: "diglett" },
  { id: 51, type: "Pokemon", identifier: "dugtrio" },
  { id: 52, type: "Pokemon", identifier: "meowth" },
  { id: 53, type: "Pokemon", identifier: "persian" },
  { id: 54, type: "Pokemon", identifier: "psyduck" },
  { id: 55, type: "Pokemon", identifier: "golduck" },
  { id: 56, type: "Pokemon", identifier: "mankey" },
  { id: 57, type: "Pokemon", identifier: "primeape" },
  { id: 58, type: "Pokemon", identifier: "growlithe" },
  { id: 59, type: "Pokemon", identifier: "arcanine" },
  { id: 60, type: "Pokemon", identifier: "poliwag" },
  { id: 61, type: "Pokemon", identifier: "poliwhirl" },
  { id: 62, type: "Pokemon", identifier: "poliwrath" },
  { id: 63, type: "Pokemon", identifier: "abra" },
  { id: 64, type: "Pokemon", identifier: "kadabra" },
  { id: 65, type: "Pokemon", identifier: "alakazam" },
  { id: 66, type: "Pokemon", identifier: "machop" },
  { id: 67, type: "Pokemon", identifier: "machoke" },
  { id: 68, type: "Pokemon", identifier: "machamp" },
  { id: 69, type: "Pokemon", identifier: "bellsprout" },
  { id: 70, type: "Pokemon", identifier: "weepinbell" },
  { id: 71, type: "Pokemon", identifier: "victreebel" },
  { id: 72, type: "Pokemon", identifier: "tentacool" },
  { id: 73, type: "Pokemon", identifier: "tentacruel" },
  { id: 74, type: "Pokemon", identifier: "geodude" },
  { id: 75, type: "Pokemon", identifier: "graveler" },
  { id: 76, type: "Pokemon", identifier: "golem" },
  { id: 77, type: "Pokemon", identifier: "ponyta" },
  { id: 78, type: "Pokemon", identifier: "rapidash" },
  { id: 79, type: "Pokemon", identifier: "slowpoke" },
  { id: 80, type: "Pokemon", identifier: "slowbro" },
  { id: 81, type: "Pokemon", identifier: "magnemite" },
  { id: 82, type: "Pokemon", identifier: "magneton" },
  { id: 83, type: "Pokemon", identifier: "farfetchd" },
  { id: 84, type: "Pokemon", identifier: "doduo" },
  { id: 85, type: "Pokemon", identifier: "dodrio" },
  { id: 86, type: "Pokemon", identifier: "seel" },
  { id: 87, type: "Pokemon", identifier: "dewgong" },
  { id: 88, type: "Pokemon", identifier: "grimer" },
  { id: 89, type: "Pokemon", identifier: "muk" },
  { id: 90, type: "Pokemon", identifier: "shellder" },
  { id: 91, type: "Pokemon", identifier: "cloyster" },
  { id: 92, type: "Pokemon", identifier: "gastly" },
  { id: 93, type: "Pokemon", identifier: "haunter" },
  { id: 94, type: "Pokemon", identifier: "gengar" },
  { id: 95, type: "Pokemon", identifier: "onix" },
  { id: 96, type: "Pokemon", identifier: "drowzee" },
  { id: 97, type: "Pokemon", identifier: "hypno" },
  { id: 98, type: "Pokemon", identifier: "krabby" },
  { id: 99, type: "Pokemon", identifier: "kingler" },
  { id: 100, type: "Pokemon", identifier: "voltorb" },
  { id: 101, type: "Pokemon", identifier: "electrode" },
  { id: 102, type: "Pokemon", identifier: "exeggcute" },
  { id: 103, type: "Pokemon", identifier: "exeggutor" },
  { id: 104, type: "Pokemon", identifier: "cubone" },
  { id: 105, type: "Pokemon", identifier: "marowak" },
  { id: 106, type: "Pokemon", identifier: "hitmonlee" },
  { id: 107, type: "Pokemon", identifier: "hitmonchan" },
  { id: 108, type: "Pokemon", identifier: "lickitung" },
  { id: 109, type: "Pokemon", identifier: "koffing" },
  { id: 110, type: "Pokemon", identifier: "weezing" },
  { id: 111, type: "Pokemon", identifier: "rhyhorn" },
  { id: 112, type: "Pokemon", identifier: "rhydon" },
  { id: 113, type: "Pokemon", identifier: "chansey" },
  { id: 114, type: "Pokemon", identifier: "tangela" },
  { id: 115, type: "Pokemon", identifier: "kangaskhan" },
  { id: 116, type: "Pokemon", identifier: "horsea" },
  { id: 117, type: "Pokemon", identifier: "seadra" },
  { id: 118, type: "Pokemon", identifier: "goldeen" },
  { id: 119, type: "Pokemon", identifier: "seaking" },
  { id: 120, type: "Pokemon", identifier: "staryu" },
  { id: 121, type: "Pokemon", identifier: "starmie" },
  { id: 122, type: "Pokemon", identifier: "mr-mime" },
  { id: 123, type: "Pokemon", identifier: "scyther" },
  { id: 124, type: "Pokemon", identifier: "jynx" },
  { id: 125, type: "Pokemon", identifier: "electabuzz" },
  { id: 126, type: "Pokemon", identifier: "magmar" },
  { id: 127, type: "Pokemon", identifier: "pinsir" },
  { id: 128, type: "Pokemon", identifier: "tauros" },
  { id: 129, type: "Pokemon", identifier: "magikarp" },
  { id: 130, type: "Pokemon", identifier: "gyarados" },
  { id: 131, type: "Pokemon", identifier: "lapras" },
  { id: 132, type: "Pokemon", identifier: "ditto" },
  { id: 133, type: "Pokemon", identifier: "eevee" },
  { id: 134, type: "Pokemon", identifier: "vaporeon" },
  { id: 135, type: "Pokemon", identifier: "jolteon" },
  { id: 136, type: "Pokemon", identifier: "flareon" },
  { id: 137, type: "Pokemon", identifier: "porygon" },
  { id: 138, type: "Pokemon", identifier: "omanyte" },
  { id: 139, type: "Pokemon", identifier: "omastar" },
  { id: 140, type: "Pokemon", identifier: "kabuto" },
  { id: 141, type: "Pokemon", identifier: "kabutops" },
  { id: 142, type: "Pokemon", identifier: "aerodactyl" },
  { id: 143, type: "Pokemon", identifier: "snorlax" },
  { id: 144, type: "Pokemon", identifier: "articuno" },
  { id: 145, type: "Pokemon", identifier: "zapdos" },
  { id: 146, type: "Pokemon", identifier: "moltres" },
  { id: 147, type: "Pokemon", identifier: "dratini" },
  { id: 148, type: "Pokemon", identifier: "dragonair" },
  { id: 149, type: "Pokemon", identifier: "dragonite" },
  { id: 150, type: "Pokemon", identifier: "mewtwo" },
  { id: 151, type: "Pokemon", identifier: "mew" },
  { id: 152, type: "Pokemon", identifier: "chikorita" },
  { id: 153, type: "Pokemon", identifier: "bayleef" },
  { id: 154, type: "Pokemon", identifier: "meganium" },
  { id: 155, type: "Pokemon", identifier: "cyndaquil" },
  { id: 156, type: "Pokemon", identifier: "quilava" },
  { id: 157, type: "Pokemon", identifier: "typhlosion" },
  { id: 158, type: "Pokemon", identifier: "totodile" },
  { id: 159, type: "Pokemon", identifier: "croconaw" },
  { id: 160, type: "Pokemon", identifier: "feraligatr" },
  { id: 161, type: "Pokemon", identifier: "sentret" },
  { id: 162, type: "Pokemon", identifier: "furret" },
  { id: 163, type: "Pokemon", identifier: "hoothoot" },
  { id: 164, type: "Pokemon", identifier: "noctowl" },
  { id: 165, type: "Pokemon", identifier: "ledyba" },
  { id: 166, type: "Pokemon", identifier: "ledian" },
  { id: 167, type: "Pokemon", identifier: "spinarak" },
  { id: 168, type: "Pokemon", identifier: "ariados" },
  { id: 169, type: "Pokemon", identifier: "crobat" },
  { id: 170, type: "Pokemon", identifier: "chinchou" },
  { id: 171, type: "Pokemon", identifier: "lanturn" },
  { id: 172, type: "Pokemon", identifier: "pichu" },
  { id: 173, type: "Pokemon", identifier: "cleffa" },
  { id: 174, type: "Pokemon", identifier: "igglybuff" },
  { id: 175, type: "Pokemon", identifier: "togepi" },
  { id: 176, type: "Pokemon", identifier: "togetic" },
  { id: 177, type: "Pokemon", identifier: "natu" },
  { id: 178, type: "Pokemon", identifier: "xatu" },
  { id: 179, type: "Pokemon", identifier: "mareep" },
  { id: 180, type: "Pokemon", identifier: "flaaffy" },
  { id: 181, type: "Pokemon", identifier: "ampharos" },
  { id: 182, type: "Pokemon", identifier: "bellossom" },
  { id: 183, type: "Pokemon", identifier: "marill" },
  { id: 184, type: "Pokemon", identifier: "azumarill" },
  { id: 185, type: "Pokemon", identifier: "sudowoodo" },
  { id: 186, type: "Pokemon", identifier: "politoed" },
  { id: 187, type: "Pokemon", identifier: "hoppip" },
  { id: 188, type: "Pokemon", identifier: "skiploom" },
  { id: 189, type: "Pokemon", identifier: "jumpluff" },
  { id: 190, type: "Pokemon", identifier: "aipom" },
  { id: 191, type: "Pokemon", identifier: "sunkern" },
  { id: 192, type: "Pokemon", identifier: "sunflora" },
  { id: 193, type: "Pokemon", identifier: "yanma" },
  { id: 194, type: "Pokemon", identifier: "wooper" },
  { id: 195, type: "Pokemon", identifier: "quagsire" },
  { id: 196, type: "Pokemon", identifier: "espeon" },
  { id: 197, type: "Pokemon", identifier: "umbreon" },
  { id: 198, type: "Pokemon", identifier: "murkrow" },
  { id: 199, type: "Pokemon", identifier: "slowking" },
  { id: 200, type: "Pokemon", identifier: "misdreavus" },
  { id: 201, type: "Pokemon", identifier: "unown" },
  { id: 202, type: "Pokemon", identifier: "wobbuffet" },
  { id: 203, type: "Pokemon", identifier: "girafarig" },
  { id: 204, type: "Pokemon", identifier: "pineco" },
  { id: 205, type: "Pokemon", identifier: "forretress" },
  { id: 206, type: "Pokemon", identifier: "dunsparce" },
  { id: 207, type: "Pokemon", identifier: "gligar" },
  { id: 208, type: "Pokemon", identifier: "steelix" },
  { id: 209, type: "Pokemon", identifier: "snubbull" },
  { id: 210, type: "Pokemon", identifier: "granbull" },
  { id: 211, type: "Pokemon", identifier: "qwilfish" },
  { id: 212, type: "Pokemon", identifier: "scizor" },
  { id: 213, type: "Pokemon", identifier: "shuckle" },
  { id: 214, type: "Pokemon", identifier: "heracross" },
  { id: 215, type: "Pokemon", identifier: "sneasel" },
  { id: 216, type: "Pokemon", identifier: "teddiursa" },
  { id: 217, type: "Pokemon", identifier: "ursaring" },
  { id: 218, type: "Pokemon", identifier: "slugma" },
  { id: 219, type: "Pokemon", identifier: "magcargo" },
  { id: 220, type: "Pokemon", identifier: "swinub" },
  { id: 221, type: "Pokemon", identifier: "piloswine" },
  { id: 222, type: "Pokemon", identifier: "corsola" },
  { id: 223, type: "Pokemon", identifier: "remoraid" },
  { id: 224, type: "Pokemon", identifier: "octillery" },
  { id: 225, type: "Pokemon", identifier: "delibird" },
  { id: 226, type: "Pokemon", identifier: "mantine" },
  { id: 227, type: "Pokemon", identifier: "skarmory" },
  { id: 228, type: "Pokemon", identifier: "houndour" },
  { id: 229, type: "Pokemon", identifier: "houndoom" },
  { id: 230, type: "Pokemon", identifier: "kingdra" },
  { id: 231, type: "Pokemon", identifier: "phanpy" },
  { id: 232, type: "Pokemon", identifier: "donphan" },
  { id: 233, type: "Pokemon", identifier: "porygon2" },
  { id: 234, type: "Pokemon", identifier: "stantler" },
  { id: 235, type: "Pokemon", identifier: "smeargle" },
  { id: 236, type: "Pokemon", identifier: "tyrogue" },
  { id: 237, type: "Pokemon", identifier: "hitmontop" },
  { id: 238, type: "Pokemon", identifier: "smoochum" },
  { id: 239, type: "Pokemon", identifier: "elekid" },
  { id: 240, type: "Pokemon", identifier: "magby" },
  { id: 241, type: "Pokemon", identifier: "miltank" },
  { id: 242, type: "Pokemon", identifier: "blissey" },
  { id: 243, type: "Pokemon", identifier: "raikou" },
  { id: 244, type: "Pokemon", identifier: "entei" },
  { id: 245, type: "Pokemon", identifier: "suicune" },
  { id: 246, type: "Pokemon", identifier: "larvitar" },
  { id: 247, type: "Pokemon", identifier: "pupitar" },
  { id: 248, type: "Pokemon", identifier: "tyranitar" },
  { id: 249, type: "Pokemon", identifier: "lugia" },
  { id: 250, type: "Pokemon", identifier: "ho-oh" },
  { id: 251, type: "Pokemon", identifier: "celebi" },
  { id: 252, type: "Pokemon", identifier: "treecko" },
  { id: 253, type: "Pokemon", identifier: "grovyle" },
  { id: 254, type: "Pokemon", identifier: "sceptile" },
  { id: 255, type: "Pokemon", identifier: "torchic" },
  { id: 256, type: "Pokemon", identifier: "combusken" },
  { id: 257, type: "Pokemon", identifier: "blaziken" },
  { id: 258, type: "Pokemon", identifier: "mudkip" },
  { id: 259, type: "Pokemon", identifier: "marshtomp" },
  { id: 260, type: "Pokemon", identifier: "swampert" },
  { id: 261, type: "Pokemon", identifier: "poochyena" },
  { id: 262, type: "Pokemon", identifier: "mightyena" },
  { id: 263, type: "Pokemon", identifier: "zigzagoon" },
  { id: 264, type: "Pokemon", identifier: "linoone" },
  { id: 265, type: "Pokemon", identifier: "wurmple" },
  { id: 266, type: "Pokemon", identifier: "silcoon" },
  { id: 267, type: "Pokemon", identifier: "beautifly" },
  { id: 268, type: "Pokemon", identifier: "cascoon" },
  { id: 269, type: "Pokemon", identifier: "dustox" },
  { id: 270, type: "Pokemon", identifier: "lotad" },
  { id: 271, type: "Pokemon", identifier: "lombre" },
  { id: 272, type: "Pokemon", identifier: "ludicolo" },
  { id: 273, type: "Pokemon", identifier: "seedot" },
  { id: 274, type: "Pokemon", identifier: "nuzleaf" },
  { id: 275, type: "Pokemon", identifier: "shiftry" },
  { id: 276, type: "Pokemon", identifier: "taillow" },
  { id: 277, type: "Pokemon", identifier: "swellow" },
  { id: 278, type: "Pokemon", identifier: "wingull" },
  { id: 279, type: "Pokemon", identifier: "pelipper" },
  { id: 280, type: "Pokemon", identifier: "ralts" },
  { id: 281, type: "Pokemon", identifier: "kirlia" },
  { id: 282, type: "Pokemon", identifier: "gardevoir" },
  { id: 283, type: "Pokemon", identifier: "surskit" },
  { id: 284, type: "Pokemon", identifier: "masquerain" },
  { id: 285, type: "Pokemon", identifier: "shroomish" },
  { id: 286, type: "Pokemon", identifier: "breloom" },
  { id: 287, type: "Pokemon", identifier: "slakoth" },
  { id: 288, type: "Pokemon", identifier: "vigoroth" },
  { id: 289, type: "Pokemon", identifier: "slaking" },
  { id: 290, type: "Pokemon", identifier: "nincada" },
  { id: 291, type: "Pokemon", identifier: "ninjask" },
  { id: 292, type: "Pokemon", identifier: "shedinja" },
  { id: 293, type: "Pokemon", identifier: "whismur" },
  { id: 294, type: "Pokemon", identifier: "loudred" },
  { id: 295, type: "Pokemon", identifier: "exploud" },
  { id: 296, type: "Pokemon", identifier: "makuhita" },
  { id: 297, type: "Pokemon", identifier: "hariyama" },
  { id: 298, type: "Pokemon", identifier: "azurill" },
  { id: 299, type: "Pokemon", identifier: "nosepass" },
  { id: 300, type: "Pokemon", identifier: "skitty" },
  { id: 301, type: "Pokemon", identifier: "delcatty" },
  { id: 302, type: "Pokemon", identifier: "sableye" },
  { id: 303, type: "Pokemon", identifier: "mawile" },
  { id: 304, type: "Pokemon", identifier: "aron" },
  { id: 305, type: "Pokemon", identifier: "lairon" },
  { id: 306, type: "Pokemon", identifier: "aggron" },
  { id: 307, type: "Pokemon", identifier: "meditite" },
  { id: 308, type: "Pokemon", identifier: "medicham" },
  { id: 309, type: "Pokemon", identifier: "electrike" },
  { id: 310, type: "Pokemon", identifier: "manectric" },
  { id: 311, type: "Pokemon", identifier: "plusle" },
  { id: 312, type: "Pokemon", identifier: "minun" },
  { id: 313, type: "Pokemon", identifier: "volbeat" },
  { id: 314, type: "Pokemon", identifier: "illumise" },
  { id: 315, type: "Pokemon", identifier: "roselia" },
  { id: 316, type: "Pokemon", identifier: "gulpin" },
  { id: 317, type: "Pokemon", identifier: "swalot" },
  { id: 318, type: "Pokemon", identifier: "carvanha" },
  { id: 319, type: "Pokemon", identifier: "sharpedo" },
  { id: 320, type: "Pokemon", identifier: "wailmer" },
  { id: 321, type: "Pokemon", identifier: "wailord" },
  { id: 322, type: "Pokemon", identifier: "numel" },
  { id: 323, type: "Pokemon", identifier: "camerupt" },
  { id: 324, type: "Pokemon", identifier: "torkoal" },
  { id: 325, type: "Pokemon", identifier: "spoink" },
  { id: 326, type: "Pokemon", identifier: "grumpig" },
  { id: 327, type: "Pokemon", identifier: "spinda" },
  { id: 328, type: "Pokemon", identifier: "trapinch" },
  { id: 329, type: "Pokemon", identifier: "vibrava" },
  { id: 330, type: "Pokemon", identifier: "flygon" },
  { id: 331, type: "Pokemon", identifier: "cacnea" },
  { id: 332, type: "Pokemon", identifier: "cacturne" },
  { id: 333, type: "Pokemon", identifier: "swablu" },
  { id: 334, type: "Pokemon", identifier: "altaria" },
  { id: 335, type: "Pokemon", identifier: "zangoose" },
  { id: 336, type: "Pokemon", identifier: "seviper" },
  { id: 337, type: "Pokemon", identifier: "lunatone" },
  { id: 338, type: "Pokemon", identifier: "solrock" },
  { id: 339, type: "Pokemon", identifier: "barboach" },
  { id: 340, type: "Pokemon", identifier: "whiscash" },
  { id: 341, type: "Pokemon", identifier: "corphish" },
  { id: 342, type: "Pokemon", identifier: "crawdaunt" },
  { id: 343, type: "Pokemon", identifier: "baltoy" },
  { id: 344, type: "Pokemon", identifier: "claydol" },
  { id: 345, type: "Pokemon", identifier: "lileep" },
  { id: 346, type: "Pokemon", identifier: "cradily" },
  { id: 347, type: "Pokemon", identifier: "anorith" },
  { id: 348, type: "Pokemon", identifier: "armaldo" },
  { id: 349, type: "Pokemon", identifier: "feebas" },
  { id: 350, type: "Pokemon", identifier: "milotic" },
  { id: 351, type: "Pokemon", identifier: "castform" },
  { id: 352, type: "Pokemon", identifier: "kecleon" },
  { id: 353, type: "Pokemon", identifier: "shuppet" },
  { id: 354, type: "Pokemon", identifier: "banette" },
  { id: 355, type: "Pokemon", identifier: "duskull" },
  { id: 356, type: "Pokemon", identifier: "dusclops" },
  { id: 357, type: "Pokemon", identifier: "tropius" },
  { id: 358, type: "Pokemon", identifier: "chimecho" },
  { id: 359, type: "Pokemon", identifier: "absol" },
  { id: 360, type: "Pokemon", identifier: "wynaut" },
  { id: 361, type: "Pokemon", identifier: "snorunt" },
  { id: 362, type: "Pokemon", identifier: "glalie" },
  { id: 363, type: "Pokemon", identifier: "spheal" },
  { id: 364, type: "Pokemon", identifier: "sealeo" },
  { id: 365, type: "Pokemon", identifier: "walrein" },
  { id: 366, type: "Pokemon", identifier: "clamperl" },
  { id: 367, type: "Pokemon", identifier: "huntail" },
  { id: 368, type: "Pokemon", identifier: "gorebyss" },
  { id: 369, type: "Pokemon", identifier: "relicanth" },
  { id: 370, type: "Pokemon", identifier: "luvdisc" },
  { id: 371, type: "Pokemon", identifier: "bagon" },
  { id: 372, type: "Pokemon", identifier: "shelgon" },
  { id: 373, type: "Pokemon", identifier: "salamence" },
  { id: 374, type: "Pokemon", identifier: "beldum" },
  { id: 375, type: "Pokemon", identifier: "metang" },
  { id: 376, type: "Pokemon", identifier: "metagross" },
  { id: 377, type: "Pokemon", identifier: "regirock" },
  { id: 378, type: "Pokemon", identifier: "regice" },
  { id: 379, type: "Pokemon", identifier: "registeel" },
  { id: 380, type: "Pokemon", identifier: "latias" },
  { id: 381, type: "Pokemon", identifier: "latios" },
  { id: 382, type: "Pokemon", identifier: "kyogre" },
  { id: 383, type: "Pokemon", identifier: "groudon" },
  { id: 384, type: "Pokemon", identifier: "rayquaza" },
  { id: 385, type: "Pokemon", identifier: "jirachi" },
  { id: 386, type: "Pokemon", identifier: "deoxys-normal" },
  { id: 387, type: "Pokemon", identifier: "turtwig" },
  { id: 388, type: "Pokemon", identifier: "grotle" },
  { id: 389, type: "Pokemon", identifier: "torterra" },
  { id: 390, type: "Pokemon", identifier: "chimchar" },
  { id: 391, type: "Pokemon", identifier: "monferno" },
  { id: 392, type: "Pokemon", identifier: "infernape" },
  { id: 393, type: "Pokemon", identifier: "piplup" },
  { id: 394, type: "Pokemon", identifier: "prinplup" },
  { id: 395, type: "Pokemon", identifier: "empoleon" },
  { id: 396, type: "Pokemon", identifier: "starly" },
  { id: 397, type: "Pokemon", identifier: "staravia" },
  { id: 398, type: "Pokemon", identifier: "staraptor" },
  { id: 399, type: "Pokemon", identifier: "bidoof" },
  { id: 400, type: "Pokemon", identifier: "bibarel" },
  { id: 401, type: "Pokemon", identifier: "kricketot" },
  { id: 402, type: "Pokemon", identifier: "kricketune" },
  { id: 403, type: "Pokemon", identifier: "shinx" },
  { id: 404, type: "Pokemon", identifier: "luxio" },
  { id: 405, type: "Pokemon", identifier: "luxray" },
  { id: 406, type: "Pokemon", identifier: "budew" },
  { id: 407, type: "Pokemon", identifier: "roserade" },
  { id: 408, type: "Pokemon", identifier: "cranidos" },
  { id: 409, type: "Pokemon", identifier: "rampardos" },
  { id: 410, type: "Pokemon", identifier: "shieldon" },
  { id: 411, type: "Pokemon", identifier: "bastiodon" },
  { id: 412, type: "Pokemon", identifier: "burmy" },
  { id: 413, type: "Pokemon", identifier: "wormadam-plant" },
  { id: 414, type: "Pokemon", identifier: "mothim" },
  { id: 415, type: "Pokemon", identifier: "combee" },
  { id: 416, type: "Pokemon", identifier: "vespiquen" },
  { id: 417, type: "Pokemon", identifier: "pachirisu" },
  { id: 418, type: "Pokemon", identifier: "buizel" },
  { id: 419, type: "Pokemon", identifier: "floatzel" },
  { id: 420, type: "Pokemon", identifier: "cherubi" },
  { id: 421, type: "Pokemon", identifier: "cherrim" },
  { id: 422, type: "Pokemon", identifier: "shellos" },
  { id: 423, type: "Pokemon", identifier: "gastrodon" },
  { id: 424, type: "Pokemon", identifier: "ambipom" },
  { id: 425, type: "Pokemon", identifier: "drifloon" },
  { id: 426, type: "Pokemon", identifier: "drifblim" },
  { id: 427, type: "Pokemon", identifier: "buneary" },
  { id: 428, type: "Pokemon", identifier: "lopunny" },
  { id: 429, type: "Pokemon", identifier: "mismagius" },
  { id: 430, type: "Pokemon", identifier: "honchkrow" },
  { id: 431, type: "Pokemon", identifier: "glameow" },
  { id: 432, type: "Pokemon", identifier: "purugly" },
  { id: 433, type: "Pokemon", identifier: "chingling" },
  { id: 434, type: "Pokemon", identifier: "stunky" },
  { id: 435, type: "Pokemon", identifier: "skuntank" },
  { id: 436, type: "Pokemon", identifier: "bronzor" },
  { id: 437, type: "Pokemon", identifier: "bronzong" },
  { id: 438, type: "Pokemon", identifier: "bonsly" },
  { id: 439, type: "Pokemon", identifier: "mime-jr" },
  { id: 440, type: "Pokemon", identifier: "happiny" },
  { id: 441, type: "Pokemon", identifier: "chatot" },
  { id: 442, type: "Pokemon", identifier: "spiritomb" },
  { id: 443, type: "Pokemon", identifier: "gible" },
  { id: 444, type: "Pokemon", identifier: "gabite" },
  { id: 445, type: "Pokemon", identifier: "garchomp" },
  { id: 446, type: "Pokemon", identifier: "munchlax" },
  { id: 447, type: "Pokemon", identifier: "riolu" },
  { id: 448, type: "Pokemon", identifier: "lucario" },
  { id: 449, type: "Pokemon", identifier: "hippopotas" },
  { id: 450, type: "Pokemon", identifier: "hippowdon" },
  { id: 451, type: "Pokemon", identifier: "skorupi" },
  { id: 452, type: "Pokemon", identifier: "drapion" },
  { id: 453, type: "Pokemon", identifier: "croagunk" },
  { id: 454, type: "Pokemon", identifier: "toxicroak" },
  { id: 455, type: "Pokemon", identifier: "carnivine" },
  { id: 456, type: "Pokemon", identifier: "finneon" },
  { id: 457, type: "Pokemon", identifier: "lumineon" },
  { id: 458, type: "Pokemon", identifier: "mantyke" },
  { id: 459, type: "Pokemon", identifier: "snover" },
  { id: 460, type: "Pokemon", identifier: "abomasnow" },
  { id: 461, type: "Pokemon", identifier: "weavile" },
  { id: 462, type: "Pokemon", identifier: "magnezone" },
  { id: 463, type: "Pokemon", identifier: "lickilicky" },
  { id: 464, type: "Pokemon", identifier: "rhyperior" },
  { id: 465, type: "Pokemon", identifier: "tangrowth" },
  { id: 466, type: "Pokemon", identifier: "electivire" },
  { id: 467, type: "Pokemon", identifier: "magmortar" },
  { id: 468, type: "Pokemon", identifier: "togekiss" },
  { id: 469, type: "Pokemon", identifier: "yanmega" },
  { id: 470, type: "Pokemon", identifier: "leafeon" },
  { id: 471, type: "Pokemon", identifier: "glaceon" },
  { id: 472, type: "Pokemon", identifier: "gliscor" },
  { id: 473, type: "Pokemon", identifier: "mamoswine" },
  { id: 474, type: "Pokemon", identifier: "porygon-z" },
  { id: 475, type: "Pokemon", identifier: "gallade" },
  { id: 476, type: "Pokemon", identifier: "probopass" },
  { id: 477, type: "Pokemon", identifier: "dusknoir" },
  { id: 478, type: "Pokemon", identifier: "froslass" },
  { id: 479, type: "Pokemon", identifier: "rotom" },
  { id: 480, type: "Pokemon", identifier: "uxie" },
  { id: 481, type: "Pokemon", identifier: "mesprit" },
  { id: 482, type: "Pokemon", identifier: "azelf" },
  { id: 483, type: "Pokemon", identifier: "dialga" },
  { id: 484, type: "Pokemon", identifier: "palkia" },
  { id: 485, type: "Pokemon", identifier: "heatran" },
  { id: 486, type: "Pokemon", identifier: "regigigas" },
  { id: 487, type: "Pokemon", identifier: "giratina-altered" },
  { id: 488, type: "Pokemon", identifier: "cresselia" },
  { id: 489, type: "Pokemon", identifier: "phione" },
  { id: 490, type: "Pokemon", identifier: "manaphy" },
  { id: 491, type: "Pokemon", identifier: "darkrai" },
  { id: 492, type: "Pokemon", identifier: "shaymin-land" },
  { id: 493, type: "Pokemon", identifier: "arceus" },
  { id: 494, type: "Pokemon", identifier: "victini" },
  { id: 495, type: "Pokemon", identifier: "snivy" },
  { id: 496, type: "Pokemon", identifier: "servine" },
  { id: 497, type: "Pokemon", identifier: "serperior" },
  { id: 498, type: "Pokemon", identifier: "tepig" },
  { id: 499, type: "Pokemon", identifier: "pignite" },
  { id: 500, type: "Pokemon", identifier: "emboar" },
  { id: 501, type: "Pokemon", identifier: "oshawott" },
  { id: 502, type: "Pokemon", identifier: "dewott" },
  { id: 503, type: "Pokemon", identifier: "samurott" },
  { id: 504, type: "Pokemon", identifier: "patrat" },
  { id: 505, type: "Pokemon", identifier: "watchog" },
  { id: 506, type: "Pokemon", identifier: "lillipup" },
  { id: 507, type: "Pokemon", identifier: "herdier" },
  { id: 508, type: "Pokemon", identifier: "stoutland" },
  { id: 509, type: "Pokemon", identifier: "purrloin" },
  { id: 510, type: "Pokemon", identifier: "liepard" },
  { id: 511, type: "Pokemon", identifier: "pansage" },
  { id: 512, type: "Pokemon", identifier: "simisage" },
  { id: 513, type: "Pokemon", identifier: "pansear" },
  { id: 514, type: "Pokemon", identifier: "simisear" },
  { id: 515, type: "Pokemon", identifier: "panpour" },
  { id: 516, type: "Pokemon", identifier: "simipour" },
  { id: 517, type: "Pokemon", identifier: "munna" },
  { id: 518, type: "Pokemon", identifier: "musharna" },
  { id: 519, type: "Pokemon", identifier: "pidove" },
  { id: 520, type: "Pokemon", identifier: "tranquill" },
  { id: 521, type: "Pokemon", identifier: "unfezant" },
  { id: 522, type: "Pokemon", identifier: "blitzle" },
  { id: 523, type: "Pokemon", identifier: "zebstrika" },
  { id: 524, type: "Pokemon", identifier: "roggenrola" },
  { id: 525, type: "Pokemon", identifier: "boldore" },
  { id: 526, type: "Pokemon", identifier: "gigalith" },
  { id: 527, type: "Pokemon", identifier: "woobat" },
  { id: 528, type: "Pokemon", identifier: "swoobat" },
  { id: 529, type: "Pokemon", identifier: "drilbur" },
  { id: 530, type: "Pokemon", identifier: "excadrill" },
  { id: 531, type: "Pokemon", identifier: "audino" },
  { id: 532, type: "Pokemon", identifier: "timburr" },
  { id: 533, type: "Pokemon", identifier: "gurdurr" },
  { id: 534, type: "Pokemon", identifier: "conkeldurr" },
  { id: 535, type: "Pokemon", identifier: "tympole" },
  { id: 536, type: "Pokemon", identifier: "palpitoad" },
  { id: 537, type: "Pokemon", identifier: "seismitoad" },
  { id: 538, type: "Pokemon", identifier: "throh" },
  { id: 539, type: "Pokemon", identifier: "sawk" },
  { id: 540, type: "Pokemon", identifier: "sewaddle" },
  { id: 541, type: "Pokemon", identifier: "swadloon" },
  { id: 542, type: "Pokemon", identifier: "leavanny" },
  { id: 543, type: "Pokemon", identifier: "venipede" },
  { id: 544, type: "Pokemon", identifier: "whirlipede" },
  { id: 545, type: "Pokemon", identifier: "scolipede" },
  { id: 546, type: "Pokemon", identifier: "cottonee" },
  { id: 547, type: "Pokemon", identifier: "whimsicott" },
  { id: 548, type: "Pokemon", identifier: "petilil" },
  { id: 549, type: "Pokemon", identifier: "lilligant" },
  { id: 550, type: "Pokemon", identifier: "basculin" },
  { id: 551, type: "Pokemon", identifier: "sandile" },
  { id: 552, type: "Pokemon", identifier: "krokorok" },
  { id: 553, type: "Pokemon", identifier: "krookodile" },
  { id: 554, type: "Pokemon", identifier: "darumaka" },
  { id: 555, type: "Pokemon", identifier: "darmanitan" },
  { id: 556, type: "Pokemon", identifier: "maractus" },
  { id: 557, type: "Pokemon", identifier: "dwebble" },
  { id: 558, type: "Pokemon", identifier: "crustle" },
  { id: 559, type: "Pokemon", identifier: "scraggy" },
  { id: 560, type: "Pokemon", identifier: "scrafty" },
  { id: 561, type: "Pokemon", identifier: "sigilyph" },
  { id: 562, type: "Pokemon", identifier: "yamask" },
  { id: 563, type: "Pokemon", identifier: "cofagrigus" },
  { id: 564, type: "Pokemon", identifier: "tirtouga" },
  { id: 565, type: "Pokemon", identifier: "carracosta" },
  { id: 566, type: "Pokemon", identifier: "archen" },
  { id: 567, type: "Pokemon", identifier: "archeops" },
  { id: 568, type: "Pokemon", identifier: "trubbish" },
  { id: 569, type: "Pokemon", identifier: "garbodor" },
  { id: 570, type: "Pokemon", identifier: "zorua" },
  { id: 571, type: "Pokemon", identifier: "zoroark" },
  { id: 572, type: "Pokemon", identifier: "minccino" },
  { id: 573, type: "Pokemon", identifier: "cinccino" },
  { id: 574, type: "Pokemon", identifier: "gothita" },
  { id: 575, type: "Pokemon", identifier: "gothorita" },
  { id: 576, type: "Pokemon", identifier: "gothitelle" },
  { id: 577, type: "Pokemon", identifier: "solosis" },
  { id: 578, type: "Pokemon", identifier: "duosion" },
  { id: 579, type: "Pokemon", identifier: "reuniclus" },
  { id: 580, type: "Pokemon", identifier: "ducklett" },
  { id: 581, type: "Pokemon", identifier: "swanna" },
  { id: 582, type: "Pokemon", identifier: "vanillite" },
  { id: 583, type: "Pokemon", identifier: "vanillish" },
  { id: 584, type: "Pokemon", identifier: "vanilluxe" },
  { id: 585, type: "Pokemon", identifier: "deerling" },
  { id: 586, type: "Pokemon", identifier: "sawsbuck" },
  { id: 587, type: "Pokemon", identifier: "emolga" },
  { id: 588, type: "Pokemon", identifier: "karrablast" },
  { id: 589, type: "Pokemon", identifier: "escavalier" },
  { id: 590, type: "Pokemon", identifier: "foongus" },
  { id: 591, type: "Pokemon", identifier: "amoonguss" },
  { id: 592, type: "Pokemon", identifier: "frillish" },
  { id: 593, type: "Pokemon", identifier: "jellicent" },
  { id: 594, type: "Pokemon", identifier: "alomomola" },
  { id: 595, type: "Pokemon", identifier: "joltik" },
  { id: 596, type: "Pokemon", identifier: "galvantula" },
  { id: 597, type: "Pokemon", identifier: "ferroseed" },
  { id: 598, type: "Pokemon", identifier: "ferrothorn" },
  { id: 599, type: "Pokemon", identifier: "klink" },
  { id: 600, type: "Pokemon", identifier: "klang" },
  { id: 601, type: "Pokemon", identifier: "klinklang" },
  { id: 602, type: "Pokemon", identifier: "tynamo" },
  { id: 603, type: "Pokemon", identifier: "eelektrik" },
  { id: 604, type: "Pokemon", identifier: "eelektross" },
  { id: 605, type: "Pokemon", identifier: "elgyem" },
  { id: 606, type: "Pokemon", identifier: "beheeyem" },
  { id: 607, type: "Pokemon", identifier: "litwick" },
  { id: 608, type: "Pokemon", identifier: "lampent" },
  { id: 609, type: "Pokemon", identifier: "chandelure" },
  { id: 610, type: "Pokemon", identifier: "axew" },
  { id: 611, type: "Pokemon", identifier: "fraxure" },
  { id: 612, type: "Pokemon", identifier: "haxorus" },
  { id: 613, type: "Pokemon", identifier: "cubchoo" },
  { id: 614, type: "Pokemon", identifier: "beartic" },
  { id: 615, type: "Pokemon", identifier: "cryogonal" },
  { id: 616, type: "Pokemon", identifier: "shelmet" },
  { id: 617, type: "Pokemon", identifier: "accelgor" },
  { id: 618, type: "Pokemon", identifier: "stunfisk" },
  { id: 619, type: "Pokemon", identifier: "mienfoo" },
  { id: 620, type: "Pokemon", identifier: "mienshao" },
  { id: 621, type: "Pokemon", identifier: "druddigon" },
  { id: 622, type: "Pokemon", identifier: "golett" },
  { id: 623, type: "Pokemon", identifier: "golurk" },
  { id: 624, type: "Pokemon", identifier: "pawniard" },
  { id: 625, type: "Pokemon", identifier: "bisharp" },
  { id: 626, type: "Pokemon", identifier: "bouffalant" },
  { id: 627, type: "Pokemon", identifier: "rufflet" },
  { id: 628, type: "Pokemon", identifier: "braviary" },
  { id: 629, type: "Pokemon", identifier: "vullaby" },
  { id: 630, type: "Pokemon", identifier: "mandibuzz" },
  { id: 631, type: "Pokemon", identifier: "heatmor" },
  { id: 632, type: "Pokemon", identifier: "durant" },
  { id: 633, type: "Pokemon", identifier: "deino" },
  { id: 634, type: "Pokemon", identifier: "zweilous" },
  { id: 635, type: "Pokemon", identifier: "hydreigon" },
  { id: 636, type: "Pokemon", identifier: "larvesta" },
  { id: 637, type: "Pokemon", identifier: "volcarona" },
  { id: 638, type: "Pokemon", identifier: "cobalion" },
  { id: 639, type: "Pokemon", identifier: "terrakion" },
  { id: 640, type: "Pokemon", identifier: "virizion" },
  { id: 641, type: "Pokemon", identifier: "tornadus" },
  { id: 642, type: "Pokemon", identifier: "thundurus" },
  { id: 643, type: "Pokemon", identifier: "reshiram" },
  { id: 644, type: "Pokemon", identifier: "zekrom" },
  { id: 645, type: "Pokemon", identifier: "landorus" },
  { id: 646, type: "Pokemon", identifier: "kyurem" },
  { id: 647, type: "Pokemon", identifier: "keldeo" },
  { id: 648, type: "Pokemon", identifier: "meloetta" },
  { id: 649, type: "Pokemon", identifier: "genesect" },
  { id: 650, type: "Pokemon", identifier: "chespin" },
  { id: 651, type: "Pokemon", identifier: "quilladin" },
  { id: 652, type: "Pokemon", identifier: "chesnaught" },
  { id: 653, type: "Pokemon", identifier: "fennekin" },
  { id: 654, type: "Pokemon", identifier: "braixen" },
  { id: 655, type: "Pokemon", identifier: "delphox" },
  { id: 656, type: "Pokemon", identifier: "froakie" },
  { id: 657, type: "Pokemon", identifier: "frogadier" },
  { id: 658, type: "Pokemon", identifier: "greninja" },
  { id: 659, type: "Pokemon", identifier: "bunnelby" },
  { id: 660, type: "Pokemon", identifier: "diggersby" },
  { id: 661, type: "Pokemon", identifier: "fletchling" },
  { id: 662, type: "Pokemon", identifier: "fletchinder" },
  { id: 663, type: "Pokemon", identifier: "talonflame" },
  { id: 664, type: "Pokemon", identifier: "scatterbug" },
  { id: 665, type: "Pokemon", identifier: "spewpa" },
  { id: 666, type: "Pokemon", identifier: "vivillon" },
  { id: 667, type: "Pokemon", identifier: "litleo" },
  { id: 668, type: "Pokemon", identifier: "pyroar" },
  { id: 669, type: "Pokemon", identifier: "flabebe" },
  { id: 670, type: "Pokemon", identifier: "floette" },
  { id: 671, type: "Pokemon", identifier: "florges" },
  { id: 672, type: "Pokemon", identifier: "skiddo" },
  { id: 673, type: "Pokemon", identifier: "gogoat" },
  { id: 674, type: "Pokemon", identifier: "pancham" },
  { id: 675, type: "Pokemon", identifier: "pangoro" },
  { id: 676, type: "Pokemon", identifier: "furfrou" },
  { id: 677, type: "Pokemon", identifier: "espurr" },
  { id: 678, type: "Pokemon", identifier: "meowstic-male" },
  { id: 679, type: "Pokemon", identifier: "honedge" },
  { id: 680, type: "Pokemon", identifier: "doublade" },
  { id: 681, type: "Pokemon", identifier: "aegislash-shield" },
  { id: 682, type: "Pokemon", identifier: "spritzee" },
  { id: 683, type: "Pokemon", identifier: "aromatisse" },
  { id: 684, type: "Pokemon", identifier: "swirlix" },
  { id: 685, type: "Pokemon", identifier: "slurpuff" },
  { id: 686, type: "Pokemon", identifier: "inkay" },
  { id: 687, type: "Pokemon", identifier: "malamar" },
  { id: 688, type: "Pokemon", identifier: "binacle" },
  { id: 689, type: "Pokemon", identifier: "barbaracle" },
  { id: 690, type: "Pokemon", identifier: "skrelp" },
  { id: 691, type: "Pokemon", identifier: "dragalge" },
  { id: 692, type: "Pokemon", identifier: "clauncher" },
  { id: 693, type: "Pokemon", identifier: "clawitzer" },
  { id: 694, type: "Pokemon", identifier: "helioptile" },
  { id: 695, type: "Pokemon", identifier: "heliolisk" },
  { id: 696, type: "Pokemon", identifier: "tyrunt" },
  { id: 697, type: "Pokemon", identifier: "tyrantrum" },
  { id: 698, type: "Pokemon", identifier: "amaura" },
  { id: 699, type: "Pokemon", identifier: "aurorus" },
  { id: 700, type: "Pokemon", identifier: "sylveon" },
  { id: 701, type: "Pokemon", identifier: "hawlucha" },
  { id: 702, type: "Pokemon", identifier: "dedenne" },
  { id: 703, type: "Pokemon", identifier: "carbink" },
  { id: 704, type: "Pokemon", identifier: "goomy" },
  { id: 705, type: "Pokemon", identifier: "sliggoo" },
  { id: 706, type: "Pokemon", identifier: "goodra" },
  { id: 707, type: "Pokemon", identifier: "klefki" },
  { id: 708, type: "Pokemon", identifier: "phantump" },
  { id: 709, type: "Pokemon", identifier: "trevenant" },
  { id: 710, type: "Pokemon", identifier: "pumpkaboo-average" },
  { id: 711, type: "Pokemon", identifier: "gourgeist-average" },
  { id: 712, type: "Pokemon", identifier: "bergmite" },
  { id: 713, type: "Pokemon", identifier: "avalugg" },
  { id: 714, type: "Pokemon", identifier: "noibat" },
  { id: 715, type: "Pokemon", identifier: "noivern" },
  { id: 716, type: "Pokemon", identifier: "xerneas" },
  { id: 717, type: "Pokemon", identifier: "yveltal" },
  { id: 718, type: "Pokemon", identifier: "zygarde" },
  { id: 719, type: "Pokemon", identifier: "diancie" },
  { id: 720, type: "Pokemon", identifier: "hoopa" },
  { id: 721, type: "Pokemon", identifier: "volcanion" },
  { id: 722, type: "Pokemon", identifier: "rowlet" },
  { id: 723, type: "Pokemon", identifier: "dartrix" },
  { id: 724, type: "Pokemon", identifier: "decidueye" },
  { id: 725, type: "Pokemon", identifier: "litten" },
  { id: 726, type: "Pokemon", identifier: "torracat" },
  { id: 727, type: "Pokemon", identifier: "incineroar" },
  { id: 728, type: "Pokemon", identifier: "popplio" },
  { id: 729, type: "Pokemon", identifier: "brionne" },
  { id: 730, type: "Pokemon", identifier: "primarina" },
  { id: 731, type: "Pokemon", identifier: "pikipek" },
  { id: 732, type: "Pokemon", identifier: "trumbeak" },
  { id: 733, type: "Pokemon", identifier: "toucannon" },
  { id: 734, type: "Pokemon", identifier: "yungoos" },
  { id: 735, type: "Pokemon", identifier: "gumshoos" },
  { id: 736, type: "Pokemon", identifier: "grubbin" },
  { id: 737, type: "Pokemon", identifier: "charjabug" },
  { id: 738, type: "Pokemon", identifier: "vikavolt" },
  { id: 739, type: "Pokemon", identifier: "crabrawler" },
  { id: 740, type: "Pokemon", identifier: "crabominable" },
  { id: 741, type: "Pokemon", identifier: "oricorio-baile" },
  { id: 742, type: "Pokemon", identifier: "cutiefly" },
  { id: 743, type: "Pokemon", identifier: "ribombee" },
  { id: 744, type: "Pokemon", identifier: "rockruff" },
  { id: 745, type: "Pokemon", identifier: "lycanroc-midday" },
  { id: 746, type: "Pokemon", identifier: "wishiwashi-solo" },
  { id: 747, type: "Pokemon", identifier: "mareanie" },
  { id: 748, type: "Pokemon", identifier: "toxapex" },
  { id: 749, type: "Pokemon", identifier: "mudbray" },
  { id: 750, type: "Pokemon", identifier: "mudsdale" },
  { id: 751, type: "Pokemon", identifier: "dewpider" },
  { id: 752, type: "Pokemon", identifier: "araquanid" },
  { id: 753, type: "Pokemon", identifier: "fomantis" },
  { id: 754, type: "Pokemon", identifier: "lurantis" },
  { id: 755, type: "Pokemon", identifier: "morelull" },
  { id: 756, type: "Pokemon", identifier: "shiinotic" },
  { id: 757, type: "Pokemon", identifier: "salandit" },
  { id: 758, type: "Pokemon", identifier: "salazzle" },
  { id: 759, type: "Pokemon", identifier: "stufful" },
  { id: 760, type: "Pokemon", identifier: "bewear" },
  { id: 761, type: "Pokemon", identifier: "bounsweet" },
  { id: 762, type: "Pokemon", identifier: "steenee" },
  { id: 763, type: "Pokemon", identifier: "tsareena" },
  { id: 764, type: "Pokemon", identifier: "comfey" },
  { id: 765, type: "Pokemon", identifier: "oranguru" },
  { id: 766, type: "Pokemon", identifier: "passimian" },
  { id: 767, type: "Pokemon", identifier: "wimpod" },
  { id: 768, type: "Pokemon", identifier: "golisopod" },
  { id: 769, type: "Pokemon", identifier: "sandygast" },
  { id: 770, type: "Pokemon", identifier: "palossand" },
  { id: 771, type: "Pokemon", identifier: "pyukumuku" },
  { id: 772, type: "Pokemon", identifier: "type-null" },
  { id: 773, type: "Pokemon", identifier: "silvally" },
  { id: 774, type: "Pokemon", identifier: "minior-red-meteor" },
  { id: 775, type: "Pokemon", identifier: "komala" },
  { id: 776, type: "Pokemon", identifier: "turtonator" },
  { id: 777, type: "Pokemon", identifier: "togedemaru" },
  { id: 778, type: "Pokemon", identifier: "mimikyu-disguised" },
  { id: 779, type: "Pokemon", identifier: "bruxish" },
  { id: 780, type: "Pokemon", identifier: "drampa" },
  { id: 781, type: "Pokemon", identifier: "dhelmise" },
  { id: 782, type: "Pokemon", identifier: "jangmo-o" },
  { id: 783, type: "Pokemon", identifier: "hakamo-o" },
  { id: 784, type: "Pokemon", identifier: "kommo-o" },
  { id: 785, type: "Pokemon", identifier: "tapu-koko" },
  { id: 786, type: "Pokemon", identifier: "tapu-lele" },
  { id: 787, type: "Pokemon", identifier: "tapu-bulu" },
  { id: 788, type: "Pokemon", identifier: "tapu-fini" },
  { id: 789, type: "Pokemon", identifier: "cosmog" },
  { id: 790, type: "Pokemon", identifier: "cosmoem" },
  { id: 791, type: "Pokemon", identifier: "solgaleo" },
  { id: 792, type: "Pokemon", identifier: "lunala" },
  { id: 793, type: "Pokemon", identifier: "nihilego" },
  { id: 794, type: "Pokemon", identifier: "buzzwole" },
  { id: 795, type: "Pokemon", identifier: "pheromosa" },
  { id: 796, type: "Pokemon", identifier: "xurkitree" },
  { id: 797, type: "Pokemon", identifier: "celesteela" },
  { id: 798, type: "Pokemon", identifier: "kartana" },
  { id: 799, type: "Pokemon", identifier: "guzzlord" },
  { id: 800, type: "Pokemon", identifier: "necrozma" },
  { id: 801, type: "Pokemon", identifier: "magearna" },
  { id: 802, type: "Pokemon", identifier: "marshadow" },
  { id: 803, type: "Pokemon", identifier: "poipole" },
  { id: 804, type: "Pokemon", identifier: "naganadel" },
  { id: 805, type: "Pokemon", identifier: "stakataka" },
  { id: 806, type: "Pokemon", identifier: "blacephalon" },
  { id: 807, type: "Pokemon", identifier: "zeraora" },
]

const types: Array<SearchInputOption> = [
  { id: TYPES.NORMAL, type: "Type", identifier: "Normal" },
  { id: TYPES.FIGHTING, type: "Type", identifier: "Fighting" },
  { id: TYPES.FLYING, type: "Type", identifier: "Flying" },
  { id: TYPES.POISON, type: "Type", identifier: "Poison" },
  { id: TYPES.GROUND, type: "Type", identifier: "Ground" },
  { id: TYPES.ROCK, type: "Type", identifier: "Rock" },
  { id: TYPES.BUG, type: "Type", identifier: "Bug" },
  { id: TYPES.GHOST, type: "Type", identifier: "Ghost" },
  { id: TYPES.STEEL, type: "Type", identifier: "Steel" },
  { id: TYPES.FIRE, type: "Type", identifier: "Fire" },
  { id: TYPES.WATER, type: "Type", identifier: "Water" },
  { id: TYPES.GRASS, type: "Type", identifier: "Grass" },
  { id: TYPES.ELECTRIC, type: "Type", identifier: "Electric" },
  { id: TYPES.PSYCHIC, type: "Type", identifier: "Psychic" },
  { id: TYPES.ICE, type: "Type", identifier: "Ice" },
  { id: TYPES.DRAGON, type: "Type", identifier: "Dragon" },
  { id: TYPES.DARK, type: "Type", identifier: "Dark" },
  { id: TYPES.FAIRY, type: "Type", identifier: "Fairy" },
]

export default HeaderInputBase
